### ISSUE TITLE
`declaration-block-properties-order` is deprecated and will be removed

### ISSUE THREAD

**Issue by chaucerbao** [cahamilton/stylelint-config-property-sort-order-smacss#1]
Any thoughts about migrating over to the recommended `stylelint-order` plugin?

https://stylelint.io/user-guide/rules/declaration-block-properties-order/

**Comment by cahamilton** [comment]
Covered in this PR: https://github.com/cahamilton/stylelint-config-property-sort-order-smacss/pull/3.
