### ISSUE TITLE
Allow for stylelint v14 (+ bump stylelint-order to v5)?

### ISSUE THREAD

**Issue by xnuk** [cahamilton/stylelint-config-property-sort-order-smacss#68]
Note: [Stylelint v14](https://github.com/stylelint/stylelint/releases/tag/14.0.0) dropped support for Node 10.

**Comment by cahamilton** [comment]
@xnuk Thanks for the heads up on this. I was waiting for v14 before I could make a few breaking changes. I'll publish a new major version to NPM soon. If there's any issues with it, let me know 👍
